name: Terraform CI/CD

on:
  push:
    branches:
      - main
      - staging
      - production

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Select Workspace
      run: terraform workspace select ${{ github.ref_name }}

    - name: Terraform Plan
      run: terraform plan -var environment=${{ github.ref_name }}

    - name: Terraform Apply
      run: terraform apply -auto-approve -var environment=${{ github.ref_name }}

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
